"""user_id FK

Revision ID: 79592101d11c
Revises: 293b725f321c
Create Date: 2026-04-20 11:09:09.741885

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79592101d11c'
down_revision: Union[str, Sequence[str], None] = '293b725f321c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'note', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'user_id')
    # ### end Alembic commands ###
