"""fixes on tables

Revision ID: e408d69c1d01
Revises: 4d37e380f345
Create Date: 2026-04-19 18:13:40.256980

"""
import sqlmodel

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e408d69c1d01'
down_revision: Union[str, Sequence[str], None] = '4d37e380f345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('note', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.drop_column('note', 'endDate')
    op.drop_column('note', 'createdAt')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.add_column('note', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('note', sa.Column('endDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('note', 'end_date')
    op.drop_column('note', 'created_at')
    # ### end Alembic commands ###
